import React from 'react'
import  AboutPageContent  from './about'


export const metadata = {
  title: ' Mawuli Stephen | Portfolio',
  description: 'Generated by Next.js',
}


function AboutPage() {
  return (
    <div>
      <AboutPageContent />
     
      {/* </SectionLayout> */}
    </div>
  )
}

export default AboutPage